id = "nyxvamp-theme"
name = "nyxvamp"
version = "0.2.0"
schema_version = 1
authors = ["zoedsoupe <zoey.spessanha@zeetech.io>"]
description = "theme inspired by transfem emo aesthetics - special for cat girls ðŸ’œðŸ˜º"
repository = "https://github.com/nyxvamp-theme/zed"
